### ISSUE TITLE
Methods don't use message parameter

### ISSUE THREAD

**Issue by hishnizza** [danisimov/gassert#1]
**List of methods**:
- verifyJsonObject(JsonObject json, String key, String message)
- verifyJsonPrimitive(JsonObject json, String key, String message)
- verifyJsonArray(JsonObject json, String key, String message)

**To do**:
- add message parameter to Assert error message
- use verifyJsonElement(JsonObject json, String key, String message) method instead of verifyJsonElement(JsonObject json, String key)

--------------------------------------------------------------------------------------------------------------------------
**List of methods**:
- verifyString(JsonObject json, String key, String value, String message)

**To do**:
- use verifyJsonPrimitive(JsonObject json, String key, String message) instead of verifyJsonPrimitive(JsonObject json, String key)

--------------------------------------------------------------------------------------------------------------------------
**List of methods**:
- verifyJsonObject(JsonObject json, String key, JsonObject value, String message)

**To do**:
- use verifyJsonObject(JsonObject json, String key, String message) instead of verifyJsonObject(JsonObject json, String key)

**Comment by danisimov** [comment]
all fixed in 1.0.10 release
